### ISSUE TITLE
123

### ISSUE THREAD

**Issue by Smalex911** [GameDevTeamPerm/IT-manager#1]

**Comment by Smalex911** [comment]
Ну как оно?

**Comment by lixich** [comment]
ну чат не очень

**Comment by Smalex911** [comment]
Почему?

**Comment by Smalex911** [comment]
он интегрирован с кодом, то есть ты правки в коде сделаешь и я могу комментарий написать прямо к строке кода

**Comment by lixich** [comment]
пол экрана заняло три сообщения
